### ISSUE TITLE
Primary Key For Every Table

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-IDS#11]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

**Author(s)**
Duane Brown
**Authoring Organization(s)**
CEDS
**Target Data Needed** 
NA
**Use Case Title**
Ensure Every Table In the IDS Contains A Primary Key

**Use Case Overview**
To allow for IDS to be longitudinal, all tables in the IDS need to have a Primary Key. This will allow for individual records to contain a start and end date. This concept has already been implemented for the tables used by the Generate application. The remainder of the tables need to be reviewed and updated to find any using a Foreign Key as their Primary Key, make those only a Foreign Key and add a Primary Key to the table.  The naming convention should be the name of the table + "Id".

**Pull Request Number(s) (If applicable)**

**Use Case Background**
To allow for the IDS to contain longitudinal data.  To be consistent with the changes already being made by the Generate states.

**Components Affected**
Delete everything from the list below except the components affected:

*CEDS Integrated Data Store (complete IDS Design Overview Table)*

*CEDS Data Migrations (complete Data Migration Impact Analysis Table)*

**CEDS Element Gap Analysis**
Provide link to CEDS Align Map or Connection.

---

**INTEGRATED DATA STORE DESIGN OVERVIEW**

**Description of Proposed Changes**
Provide a concise description of the proposed changes. 

**As-Is Diagram**
Add as an attachment in this issue.

**Proposed To-Be Diagram**
Add as an attachment in this issue.

---

**DATA WAREHOUSE DESIGN OVERVIEW (Includes Dim, Fact, and Report tables)**

**Description of Proposed Changes**
Provide a concise description of the proposed changes.

**As-Is Diagram**
Add as an attachment in this issue.

**Proposed To-Be Diagram**
Add as an attachment in this issue.

---

**DATA MIGRATION IMPACT ANALYSIS**

**Description of Proposed Changes**
Provide a concise description of the proposed changes.

**New Business Rule**
Provide a concise and comprehensive description of the new business rule.

**Existing Business Rule**
Provide a concise and comprehensive description of the existing business rule.

**Changed Business Rule**
Provide a concise and comprehensive description of the changes to be made to the business rule.

**Comment by jillparkesQIP** [comment]
Primary keys were added to missing tables in the 8.0.0.0 branch release.
