### ISSUE TITLE
Managing deprecated option set values in reference ("Ref") tables

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-IDS#12]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

**Author(s)**
Nathan Clinton

**Authoring Organization(s)**
CEDS

**Target Data Needed**
N/A

**Use Case Title**
Managing deleted or deprecated CEDS option set codes in the IDS to support longitudinal data and also maintaining and identifying the current official CEDS option set in the IDS. 

**Use Case Overview**
In cases where a code is deprecated, stakeholders need to be able to:
1) Store longitudinal data -- If the deprecated code was used, then we need to keep the record in the Ref table in order to maintain both accurate longitudinal data and basic referential integrity.
2) Identify the official CEDS option set values based at any given time -- If a system provides, for example, a drop down list that pulls from the Ref tables, there needs to be a way to select the correct list of options as of a particular date.  

**Pull Request Number(s) (If applicable)**

**Use Case Background**
The NCES form has recommended removing the code "Exited" from "Exit or Withdrawal Type" ([CEDS Elements Issue 5 ](https://github.com/CEDStandards/CEDS-Elements/issues/5)).  If this code is deprecated, we need to be able to support stakeholders using this code the IDS.

**Components Affected**
Delete everything from the list below except the components affected:

*CEDS Integrated Data Store (complete IDS Design Overview Table)*

**CEDS Element Gap Analysis**
[CEDS Elements Issue 5 ](https://github.com/CEDStandards/CEDS-Elements/issues/5)

---

***INTEGRATED DATA STORE DESIGN OVERVIEW***

**Description of Proposed Changes**
Provide a concise description of the proposed changes. 
Add the following fields to all Ref tables:
1) RecordStartDateTime
2) RecordEndDateTime

New option set values will be assigned a RecordStartDateTimethat corresponds with the date when the option was made available in CEDS and the IDS.

RecordEndDateTime will be null for currently active option set values.

A date will be assigned to RecordEndDateTime that corresponds with the date when the option was officially deprecated.  

**As-Is Diagram**
N/A

**Proposed To-Be Diagram**
N/A

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
