### ISSUE TITLE
Postsecondary Exit or Withdrawal Type is a product of a student's PS institution enrollment, not a PS program enrollment

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-IDS#14]
**Describe the bug**

PsExitOrWithdrawalType is in PsProgram, but it should be in PsStudentEnrollment.  The definition and option set values work better in that table, and the CEDS Element in the DES is in Postsecondary -> PS Student -> Institution Enrollment.

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
