### ISSUE TITLE
The field Organization.RegionGeoJSON can change over time, so move it to OrganizationDetail

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-IDS#15]
**Describe the bug**

We want to be able to track an organization's region data over time, which means it needs to be moved to OrganizationDetail.

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
