### ISSUE TITLE
Rubric/RubricCriterion join to CompetencySet

### ISSUE THREAD

**Issue by jgoodell2** [CEDStandards/CEDS-IDS#2]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Ex. I'm always frustrated when [...]
The current model doesn't support the use case of a Rubric or Rubric Criterion used to evaluate a Competency Set (e.g. a complex performance task that requires 2 or more competencies).

**Describe the solution you'd like**

Add join table between Rubric/RubricCriterion and CompetencySet?
--

**Describe alternatives you've considered**

**Additional context**

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
