### ISSUE TITLE
RefTitleIIILanguageInstructionProgramType Identical SortOrder Values

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-IDS#22]
**Describe the bug**
The IDS Reference Table "RefTitleIIILanguageInstructionProgramType" contains two identical SortOrder values.

**To Reproduce**

SELECT *
FROM dbo.RefTitleIIILanguageInstructionProgramType

The Code of "NewcomerPrograms" and the Code of "Other" both have a SortOrder of "11.00"

**Expected behavior**
Modify the row with the code of "Other" to have a SortOrder of "12.00"

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
