### ISSUE TITLE
Ref Table Description Values Longer than character limit

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#23]
**Describe the bug**
Currently Description in Ref tables is a nvarchar(100) however several reference tables have values in the populating script that are truncated to fit this length. In most cases these seem to be small, only 1-3 characters and it's straightforward to interpolate what's being cut off, but in others it's hard to tell just what's being cut off. Currently these tables are:
RefCarnegieBasicClassification
RefCourseSectionExitType
RefExitOrWithdrawalType
RefIPEDSFASBFinancialPosition
RefPESCAwardLevelType
RefProgramExitReason
RefProgramGiftedEligibility
RefRlisProgramUse
RefTribalAffiliation

**To Reproduce**
1. Go to 'Populate-CEDS-Ref-Tables.sql'
2. Search for one of the above tables
3. Locate record that is truncated. For example RefPESCAwardLevelType has a Description with the value 'Postsecondary award, certificate, or diploma of less than one academic year (less than 900 contact o' and it's unclear at a quick glance just what's being lost with the truncation.

**Expected behavior**
I'd expect the Description field to be long enough to hold all values without truncation

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
