### ISSUE TITLE
K12Course.RefCreditTypeEarnedId in IDS is a required field

### ISSUE THREAD

**Issue by lkommuri** [CEDStandards/CEDS-IDS#24]
The RefCreditTypeEarnedId attribute in IDS is set as a required field while that data is not available in our use case. This is preventing us from storing values in this table. 

**Expected behavior**
Requesting to make changes so that null values for this field can be allowed.

**Comment by AEMDuaneBrown** [comment]
Just to clarify - the table you are referencing is the K12Course table correct. I see that it can be NULL in every other table except this one, but I want to be sure this is the table you are referencing.

**Comment by lkommuri** [comment]
Yes, that is correct. Its - K12Course.RefCreditTypeEarnedId

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
