### ISSUE TITLE
RefStateANSICode does not follow the design pattern of other reference tables

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#25]
**Describe the bug**
RefStateANSICode has only two columns: Code and StateName, which is very different from other reference tables and their structure.

**To Reproduce**
See description

**Expected behavior**
We'd expect the design of the RefStateANSICode to match that of other reference tables

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
