### ISSUE TITLE
RefTitleISchoolStatus has a misnamed primary key

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#26]
**Describe the bug**
The reference table RefTitleISchoolStatus has a primary key named RefTitle1SchoolStatusId (note the numeric rather than roman numeral), which is not consistent with the table name or other similar tables.

**To Reproduce**
See description

**Expected behavior**
We'd expect the name of the primary key to be RefTitleISchoolStatusId

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
