### ISSUE TITLE
The primary key of RefHighSchoolGraduationRateIndicator is not consistent with naming conventions

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#30]
**Describe the bug**
The primary key of RefHighSchoolGraduationRateIndicator is currently RefHSGraduationRateIndicatorId when by typical naming conventions used in the IDS it should be RefHighSchoolGraduationRateIndicatorId

**To Reproduce**
See description

**Expected behavior**
We'd except the primary key to be named RefHighSchoolGraduationRateIndicatorId

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
