### ISSUE TITLE
Column FacilityAcquisitionDate in Facility is of type nvarchar instead of date

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#32]
**Describe the bug**
The column FacilityAcquisitionDate in Facility is currently a nvarchar[100]. However the definition of the associated CEDS Element https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=47092 is a date format value. In other cases within the CEDS-IDS Date format elements are typed as Date, not nvarchar.

**To Reproduce**
See description

**Expected behavior**
We'd expect FacilityAcquisitionDate to be a Date type column.

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
