### ISSUE TITLE
IDS – Need Mechanism to Track Data by Collection

### ISSUE THREAD

**Issue by CEPIkconroy** [CEDStandards/CEDS-IDS#35]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

Author(s)
Karen Conroy
Jeremy Avery

Authoring Organization(s)
Center for Education Performance and Information (CEPI) in Michigan

Email Address
conroyk@michigan.gov

Target Data Needed
We're coding this at CEPI and will submit the change to the community once the project is complete.

Use Case Title
Need mechanism to track data by collection.

Use Case Overview
Add mechanism to track data by collection so that we can differentiate in the IDS and Data Warehouse what data to use for reporting use cases.

**Pull Request Number(s) (If applicable)**

**Use Case Background**
Michigan needs mechanism to track collection data over time.  See attached spreadsheet 'Michigan Data Collection Elements' with needed data element information.

[Michigan Data Collection Elements.xlsx](https://github.com/CEDStandards/CEDS-IDS/files/4961887/Michigan.Data.Collection.Elements.xlsx)

**Components Affected**
Delete everything from the list below except the components affected:

*CEDS Integrated Data Store (complete IDS Design Overview Table)*

*CEDS Data Warehouse (complete DW Design Overview Table)*

*CEDS Data Migrations (complete Data Migration Impact Analysis Table)*

**CEDS Element Gap Analysis**
Provide link to CEDS Align Map or Connection.

---

**INTEGRATED DATA STORE DESIGN OVERVIEW**

**Description of Proposed Changes**
Provide a concise description of the proposed changes. 

**As-Is Diagram**
Add as an attachment in this issue.

**Proposed To-Be Diagram**
Add as an attachment in this issue.

---

**DATA WAREHOUSE DESIGN OVERVIEW (Includes Dim, Fact, and Report tables)**

**Description of Proposed Changes**
Provide a concise description of the proposed changes.

**As-Is Diagram**
Add as an attachment in this issue.

**Proposed To-Be Diagram**
Add as an attachment in this issue.

---

**DATA MIGRATION IMPACT ANALYSIS**

**Description of Proposed Changes**
Provide a concise description of the proposed changes.

**New Business Rule**
Provide a concise and comprehensive description of the new business rule.

**Existing Business Rule**
Provide a concise and comprehensive description of the existing business rule.

**Changed Business Rule**
Provide a concise and comprehensive description of the changes to be made to the business rule.

**Comment by AEMDuaneBrown** [comment]
Elements relate to "data collection" are pending approval in this ticket:
https://github.com/CEDStandards/CEDS-Elements/issues/251
If approved in the CEDS-Elements process, they will satisfy the requirements of this ticket when modeled in the IDS.

**Comment by AEMDuaneBrown** [comment]
The Version 9.0.1.0 release of the IDS contains the Data Collection information from Elements Issue 251 (https://github.com/CEDStandards/CEDS-Elements/issues/251)
