### ISSUE TITLE
Add New Table K12LeaGradeOffered

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-IDS#37]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

**Author(s)**
Duane Brown

**Authoring Organization(s)**
CIID Generate

**Email Address**
duane.brown@aemcorp.com

**Use Case Title**
Add New Table K12LeaGradeOffered

**Use Case Overview**
Create a new table in the CEDS Integrated Data Store called K12LeaGradeOffered.  This will be used to track the Grades Offered by an LEA. The new table will include the following columns:

K12LeaGradeOfferedId (PK, int, not null)
K12LeaId (FK, in, not null)
RefGradeLevelId (FK, int, not null)
RecordStartDateTime (datetime, null)
RecordEndDateTime (datetime, null)

**Pull Request Number(s) (If applicable)**

**Use Case Background**
Provide information related to why these changes/additions are needed.
This change is in reference to the Elements Issue that is presently pending community approval listed here:
https://github.com/CEDStandards/CEDS-Elements/issues/133

The proposal will provide the needed background for the change. Essentially, the grades offered by the schools under the authority of an LEA do not always equal the grades offered by the LEAs. In some states, LEAs offer additional grades beyond what their schools are able to offer and this is done through agreements/contracts with other LEAs. Therefore this information must be tracked separately.

**Components Affected**
Delete everything from the list below except the components affected:

*CEDS Integrated Data Store (complete IDS Design Overview Table)*

New table: K12LeaGradeOffered
Columns:
K12LeaGradeOfferedId (PK, int, not null)
K12LeaId (FK, in, not null)
RefGradeLevelId (FK, int, not null)
RecordStartDateTime (datetime, null)
RecordEndDateTime (datetime, null)

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
