### ISSUE TITLE
The RefRace table for IDS v8.0.0.0 has invalid codes

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-IDS#39]
**Describe the bug**
The script that populates the RefRace table for the IDS for V8.0.0.0 contains invalid codes. The script needs to be modified to reflect the correct coding for races.

**To Reproduce**
SELECT * FROM RefRace

**Expected behavior**
The Code column should contain the following:
AmericanIndianorAlaskaNative
Asian
BlackorAfricanAmerican
NativeHawaiianorOtherPacificIslander
White

It presently contains:
Race American Indian or Alaska Native
Race Asian
Race Black or African American
Race Native Hawaiian or Other Pacific Islander
Race White

Modify the script to reflect the correct race codes.

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
