### ISSUE TITLE
DiplomaOrCredentialAwardDate data type inconsistency

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#40]
**Describe the bug**
DiplomaOrCredentialAwardDate has a data type mismatch. It's a datetime in K12StudentAcademicRecord but a NVARCHAR(7) in other tables. 

**To Reproduce**
Search for DiplomaOrCredentialAwardDate in the CEDS-IDS sql script.

**Expected behavior**
We'd expect DiplomaOrCredentialAwardDate to have the same data type in all tables.

**Comment by jillparkesQIP** [comment]
Addressed in V9.0.0.0 release, #42. See [CEDS OSC IDS Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-IDS/blob/master/doc/CEDS%20OSC%20IDS%20Summary%20v9%20Changes.xlsx) for additional details.
