### ISSUE TITLE
Expand Personal Information Verification to be a 1:Many relationship in CEDS-IDS

### ISSUE THREAD

**Issue by EricMarshallNC** [CEDStandards/CEDS-IDS#43]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

**Author(s)**
Eric Marshall
**Authoring Organization(s)**
North Carolina Department of Public Instruction
**Email Address**
eric.marshall@dpi.nc.gov
**Use Case Title**
Expand Personal Information Verification to be a 1:Many relationship.

**Use Case Overview**
Expand Expand Personal Information Verification (000618) currently stored in PersonDetail to be a 1:Many relationship to allow multiple sources of verification to be stored.

**Pull Request Number(s) (If applicable)**
N/A

**Use Case Background**
Currently in the CEDS-IDS only one source of personal information verification can be stored for a person. However, one person may provide multiple sources of verification due to various factors, such as a single document not verifying all personal information. North Carolina would like to be able to store all of these verification sources.

**Components Affected**

*CEDS Integrated Data Store (complete IDS Design Overview Table)*

---

**INTEGRATED DATA STORE DESIGN OVERVIEW**

**Description of Proposed Changes**
We'd like to add a new table, proposed name PersonPersonalInformationVerification, to create a 1:Many relationship between Person and RefPersonalInformationVerification, which is currently a 1:1 relationship found in PersonDetail as field RefPersonalInformationVerificationId. This would be similar to other currently existing tables such as PersonLanguage.

At present it would only have RefPersonalInformationVerificationId as a data field, making the SQL look something like:

CREATE TABLE [dbo].[PersonPersonalInformationVerification](
	[PersonPersonalInformationVerificationId] [int] IDENTITY(1,1) NOT NULL,
	[PersonId] [int] NOT NULL,
	[RefPersonalInformationVerificationId] [int] NOT NULL,
	[RecordStartDateTime] [datetime] NULL,
	[RecordEndDateTime] [datetime] NULL,
 CONSTRAINT [PK_PersonPersonalInformationVerification] PRIMARY KEY CLUSTERED 
(
	[PersonPersonalInformationVerificationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

This would also entail removing/deprecating RefPersonalInformationVerificationId from PersonDetail

---

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 43 (Note this proposal is linked to the elements proposal 60 (https://github.com/CEDStandards/CEDS-Elements/issues/60)

[Personal Information Verification Issue_60.docx](https://github.com/CEDStandards/CEDS-IDS/files/7107679/Personal.Information.Verification.Issue_60.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V10.0.0.0 release, [CEDS V10.0.0.0 Release Candidate Changes.](https://github.com/CEDStandards/CEDS-IDS/commit/e6e77c3f429f0f884b6981f2211f5e8b2580dd9f) for additional details.
