### ISSUE TITLE
Create a Version Table in the IDS

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-IDS#45]
This is for capturing needs not currently supported by the CEDS model. Please do not send or share actual data as examples in this issue or in attachments.

**Author(s)**
Duane Brown
**Authoring Organization(s)**
CEDS Team
**Email Address**
duane.brown@aemcorp.com
**Use Case Title**
Create a Version Table in the IDS

**Use Case Overview**
Create a table in the CEDS IDS that houses the Version of the IDS (e.g. 9.0.0.0)

**Pull Request Number(s) (If applicable)**

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Components Affected**
Delete everything from the list below except the components affected:

*CEDS Integrated Data Store (complete IDS Design Overview Table)*

*CEDS Data Warehouse (complete DW Design Overview Table)*

*CEDS Data Migrations (complete Data Migration Impact Analysis Table)*

**CEDS Element Gap Analysis**
Provide link to CEDS Align Map or Connection.

---

**INTEGRATED DATA STORE DESIGN OVERVIEW**

**Description of Proposed Changes**
Provide a concise description of the proposed changes. 

**As-Is Diagram**
Add as an attachment in this issue.

**Proposed To-Be Diagram**
Add as an attachment in this issue.

---

**DATA WAREHOUSE DESIGN OVERVIEW (Includes Dim, Fact, and Report tables)**

**Description of Proposed Changes**
Provide a concise description of the proposed changes.

**As-Is Diagram**
Add as an attachment in this issue.

**Proposed To-Be Diagram**
Add as an attachment in this issue.

---

**DATA MIGRATION IMPACT ANALYSIS**

**Description of Proposed Changes**
Provide a concise description of the proposed changes.

**New Business Rule**
Provide a concise and comprehensive description of the new business rule.

**Existing Business Rule**
Provide a concise and comprehensive description of the existing business rule.

**Changed Business Rule**
Provide a concise and comprehensive description of the changes to be made to the business rule.

**Comment by jillparkesQIP** [comment]
Addressed in V10.0.0.0 release, [CEDS V10.0.0.0 Release Candidate Changes.](https://github.com/CEDStandards/CEDS-IDS/commit/e6e77c3f429f0f884b6981f2211f5e8b2580dd9f) for additional details.

**Comment by AEMDuaneBrown** [comment]
Completed in Version 10.0.0.0 - closing
